//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingBKOT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySale
    {
        public long id { get; set; }
        public Nullable<int> TableNum { get; set; }
        public string ServiceType { get; set; }
        public Nullable<int> Qty { get; set; }
        public string ItemName { get; set; }
        public string ItemPrice { get; set; }
        public string empID { get; set; }
        public string OrderDate { get; set; }
        public string OrderTime { get; set; }
        public string statues { get; set; }
        public string KOT { get; set; }
    }
}
