//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingBKOT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class detailsSettlement
    {
        public string KOT { get; set; }
        public System.DateTime paidDate { get; set; }
        public string paidTime { get; set; }
        public string currencyInUsed { get; set; }
        public decimal bill { get; set; }
        public string custCurrencyChosen { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<decimal> changeDue { get; set; }
        public string paymentType { get; set; }
        public string acctName { get; set; }
        public string acctNum { get; set; }
        public string electronicType { get; set; }
        public string empID { get; set; }
    }
}
