//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingBKOT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogHistory
    {
        public int id { get; set; }
        public string empID { get; set; }
        public System.DateTime logDate { get; set; }
        public string logTime { get; set; }
        public System.DateTime endShiftDate { get; set; }
        public string endShiftTime { get; set; }
        public string statues { get; set; }
    }
}
