//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingBKOT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCurrency
    {
        public int curID { get; set; }
        public string CurName { get; set; }
        public string curSymbol { get; set; }
        public string Statues { get; set; }
        public string convertAmt { get; set; }
    }
}
