//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingBKOT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int id { get; set; }
        public string empID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string oname { get; set; }
        public string gender { get; set; }
        public System.DateTime dob { get; set; }
        public string phone { get; set; }
        public string resAddress { get; set; }
        public string emailAdd { get; set; }
        public string ref_fname { get; set; }
        public string ref_lname { get; set; }
        public string ref_phone { get; set; }
        public byte[] photo { get; set; }
    }
}
