//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingBKOT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderInfo
    {
        public long id { get; set; }
        public string orderType { get; set; }
        public string tableNo { get; set; }
        public string KOT { get; set; }
        public System.DateTime ordDate { get; set; }
        public string ordTime { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string adultNo { get; set; }
        public string childrenNo { get; set; }
        public string empID { get; set; }
        public string waiterId { get; set; }
        public string mobile { get; set; }
    }
}
