//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingBKOT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTax
    {
        public int taxID { get; set; }
        public decimal tax_1 { get; set; }
        public Nullable<decimal> tax_2 { get; set; }
        public Nullable<decimal> tax_3 { get; set; }
    }
}
